# Generated by Django 5.1.6 on 2025-07-11 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoStock', '0001_initial'),
        ('producto', '0003_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='producto.producto'),
        ),
    ]
